'use strict';

var NS = exports.NAMESPACES = {
    HTML:   'http://www.w3.org/1999/xhtml',
    MATHML: 'http://www.w3.org/1998/Math/MathML',
    SVG:    'http://www.w3.org/2000/svg',
    XLINK:  'http://www.w3.org/1999/xlink',
    XML:    'http://www.w3.org/XML/1998/namespace',
    XMLNS:  'http://www.w3.org/2000/xmlns/'
};

var SPECIAL_ELEMENTS = exports.SPECIAL_ELEMENTS = {};

SPECIAL_ELEMENTS[NS.HTML] = {
    'address':    true,
    'applet':     true,
    'area':       true,
    'article':    true,
    'aside':      true,
    'base':       true,
    'basefont':   true,
    'bgsound':    true,
    'blockquote': true,
    'body':       true,
    'br':         true,
    'button':     true,
    'caption':    true,
    'center':     true,
    'col':        true,
    'colgroup':   true,
    'dd':         true,
    'details':    true,
    'dir':        true,
    'div':        true,
    'dl':         true,
    'dt':         true,
    'embed':      true,
    'fieldset':   true,
    'figcaption': true,
    'figure':     true,
    'footer':     true,
    'form':       true,
    'frame':      true,
    'frameset':   true,
    'h1':         true,
    'h2':         true,
    'h3':         true,
    'h4':         true,
    'h5':         true,
    'h6':         true,
    'head':       true,
    'header':     true,
    'hgroup':     true,
    'hr':         true,
    'html':       true,
    'iframe':     true,
    'img':        true,
    'input':      true,
    'isindex':    true,
    'li':         true,
    'link':       true,
    'listing':    true,
    'main':       true,
    'marquee':    true,
    'menu':       true,
    'menuitem':   true,
    'meta':       true,
    'nav':        true,
    'noembed':    true,
    'noframes':   true,
    'noscript':   true,
    'object':     true,
    'ol':         true,
    'p':          true,
    'param':      true,
    'plaintext':  true,
    'pre':        true,
    'script':     true,
    'section':    true,
    'select':     true,
    'source':     true,
    'style':      true,
    'summary':    true,
    'table':      true,
    'tbody':      true,
    'td':         true,
    'template':   true,
    'textarea':   true,
    'tfoot':      true,
    'th':         true,
    'thead':      true,
    'title':      true,
    'tr':         true,
    'track':      true,
    'ul':         true,
    'wbr':        true,
    'xmp':        true
};


SPECIAL_ELEMENTS[NS.MATHML] = {
    'mi':             true,
    'mo':             true,
    'mn':             true,
    'ms':             true,
    'mtext':          true,
    'annotation-xml': true
};

SPECIAL_ELEMENTS[NS.SVG] = {
    'title':         true,
    'foreignObject': true,
    'desc':          true
};
